[workspace]
resolver = "3"
members = ["std", "dos_rt", "dos"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Abbie <abbiepup@proton.me>"]
repository = "https://github.com/abbiepup/libdos"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
