[package]
name = "std"
version = "0.1.0"
edition = "2024"

[dependencies]
dos = { path = "../dos" }
thiserror = { version = "2.0.17", default-features = false }

[lints.rust]
internal_features = "allow"
