[package]
name = "dos"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bios = { path = "../bios" }
thiserror = { version = "2.0.17", default-features = false }
